### ISSUE TITLE
Private methods should be private

### ISSUE THREAD

**Issue by lolgab** [david-bouyssie/sqlite4s#1]
Methods like this, with name prefixed with underscore to use Scala and java API should be private in my opinion. https://github.com/david-bouyssie/sqlite4s/blob/2d2c64fe0c1e272aaac3ef84be88c00c31b4222c/src/main/scala/com/github/sqlite4s/SQLite.scala#L39

**Comment by david-bouyssie** [comment]
It seems I forgot it during code translation...
